name: CI for taqy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - name: Check out code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8 black pandas wrds fastparquet pyarrow

    - name: Install taqy
      run: |
        pip install -e .

    - name: Run tests
      run: |
        pytest

    - name: Check formatting with black
      run: black . --check

    - name: Run linting with flake8
      run: flake8 --ignore=E501,E266,W291 .

    - name: Install build tools
      run: |
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Publish package to PyPI
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m twine upload --verbose --skip-existing dist/*
